print ( ' CONSTRUCTING THE FOLLOWING PATTERN ')
print ('                ')
print ('*')
print ('* *')
print ('* * *')
print ('* * * *')
print ('* * * * *')
print ('* * * *')
print ('* * *')
print ('* *')
print ('*')